### PR TITLE
readme WIP

### PR DESCRIPTION
**Pull request by Stupefacient**

### CODE REVIEW

**Comment by Stupefacient** [comment]
should we make a features..md that links to the main readme?

**Comment by rav4kumar** [comment]
Definitely!

**Review by danpadure — CHANGES_REQUESTED** [review]
"dragonpilot performs the functions of forms the functions"
change this, please

**Comment by Stupefacient** [comment]
Yeah yeah yeah yeah I'm getting to it someday

**Review by eFiniLan — COMMENTED** [review]
thanks Stupefacient! :)

**Comment by Gamerios** [comment]
also how can connect your branch to : https://github.com/florianbrede-ayet/retropilot-server   ?

**Pull request closed without merging**
