### PR TITLE
Fix lateral planner laneless mode

### PR DESCRIPTION
**Pull request by Hikari1023**
modes seem reverse

### CODE REVIEW

**Comment by Hikari1023** [comment]
Compared with stock OP.
This bug started from DP 0.8.12

**Review by Hikari1023 — COMMENTED** [review]
compare stock op 813 (left) with dp 813 testing  (right)
dp_testing

**Comment by eFiniLan** [comment]
@Hikari1023 Thanks very much for the fix! that looks good to me, @rav4kumar you think?

**Comment by sunnyhaibin** [comment]
@eFiniLan This fix looks good. I mentioned this in this issue :) I applied the fix and the models now work as expected:
https://github.com/sunnyhaibin/openpilot/issues/16

**Comment by eFiniLan** [comment]
hehe... thanks @sunnyhaibin and @Hikari1023 
👍 💯

**Pull request merged**
