### PR TITLE
Honda odyssey hybrid 2022 China version support

### PR DESCRIPTION
**Pull request by lijunhao731**
Honda odyssey hybrid 2022 China version(nidec) has two f-can buses,so need to add a proxy board(functions like a panda) to combine those two can buses together.
Tested onroad.

### CODE REVIEW

**Comment by Stupefacient** [comment]
See on where to commit if you want it upstreamed

https://github.com/dragonpilot-community#community-and-contributing

**Comment by lijunhao731** [comment]
> See on where to commit if you want it upstreamed
> 
> https://github.com/dragonpilot-community#community-and-contributing

Does dp-devel:master support eon? I have no C3 to test.

**Comment by Stupefacient** [comment]
Yes. We develop for master than have a script make it into release2 and release3 branches

**Comment by rav4kumar** [comment]
ill get it merged! @lijunhao731 next time please pr to https://github.com/dragonpilot-community/dp-private. PR get automatically  closed when we push new releases.

Cheers,

**Pull request closed without merging**
