### PR TITLE
Add volvo support to Dragonpilot

### PR DESCRIPTION
**Pull request by chiachunli08**
Big thanks to @danielzmod for the volvo part
*allow gas not working.
*volvo-carcontroller, dp-blinker part not working.

### CODE REVIEW

**Comment by Stupefacient** [comment]
Please rebased off master based in DP devel repro thank you for the pr

**Comment by Stupefacient** [comment]
https://github.com/dragonpilot-community/dp-devel

**Comment by chiachunli08** [comment]
Hi, I only test this on my EON at 0.8.13.
I don't have a comma 3 to test with if I merge them with the master base.

**Comment by Stupefacient** [comment]
0.8.13 isn’t being actively supported. Release2 and beta2 are currently being supported and maintained off Master. Nothing your pr specific to EON so rebasing shouldn’t be an issue. Once again development takes on DP devel repro not here

**Comment by chiachunli08** [comment]
@Stupefacient do I have to keep the dragonconf part? or just leave it original?

**Comment by Stupefacient** [comment]
Kumar going to rebase it and add it master. Thank you man. Look forward to in either next week or week after R2e2e or beta2

**Comment by leomonde** [comment]
Why in 0.8.13 there is Volvo support in selfdrive/car/volvo and in later releases, like release2 or release3, the folder selfdrive/car/volvo is missing?

**Pull request merged**
