### PR TITLE
1. Toyota/Lexus: Allow 5 mph/kph speed increments 2. fix translate errors 0.8.9

### PR DESCRIPTION
**Pull request by betashepherd**
Toyota NODSU Hybrid: Allow 5 mph/kph speed increments

### CODE REVIEW

**Comment by rav4kumar** [comment]
It’s already in 0.8.10 not sure if we want to maintain it for older version.

**Comment by betashepherd** [comment]
> It’s already in 0.8.10 not sure if we want to maintain it for older version.

I have already tested 0.8.10, the main difference :
1. the distance to the leader car become much longer
2. ret.startAccel = 1.0  # Accelerate from 0 faster
both of them make other cars cut in, that's make driving not chill.

**Comment by betashepherd** [comment]
if button_type:
    v_cruise_kph = math.floor(v_cruise_kph)
  
  after n time change v it will not accuracy, this fix long v accuracy.

**Comment by rav4kumar** [comment]
Add it to all the dbc in Toyota then we can merge it.

**Comment by rav4kumar** [comment]
> ret.startAccel = 1.0

add it under your car only. Do not change it for all the interface. If people like it then we can change it later on.

**Comment by betashepherd** [comment]
> Add it to all the dbc in Toyota then we can merge it.

ok

**Comment by betashepherd** [comment]
update all support long-press +5 kph Toyota/Lexus DBC files

**Comment by betashepherd** [comment]
@rav4kumar

**Pull request merged**
