### PR TITLE
Update krkeegan's long control to the latest state

### PR DESCRIPTION
**Pull request by CT921**
．Stop Harsh Braking, Remove Cost Multipliers on Deceleration
．Pass Keyword Args, Not Positional, for Future Compatibility
．longitudinal planner: disable change cost when stopped. not engaged or gas pressed
．Set in Update; Remove Set_Weights from Planner

Original author: krkeegan
https://github.com/krkeegan/openpilot/commits/feature_fix_slow_start

### CODE REVIEW

**Comment by rav4kumar** [comment]
this need some more testing before merging. It might brake mapd controls.

**Comment by CT921** [comment]
> this need some more testing before merging. It might brake mapd controls.


Did you mean the VisionTurnController?

**Comment by rav4kumar** [comment]
> > this need some more testing before merging. It might brake mapd controls.
> 
> Did you mean the VisionTurnController?

Yes, also turn and speed limit controller as well.

**Comment by CT921** [comment]
> turn and speed limit controller


VisionTurnController added this commit is smoother. But the turn and speed limit controller is not tested because I always disable it...

**Comment by rav4kumar** [comment]
we will see if can merge this pr in the future. thank you

**Pull request closed without merging**
